package database

import (
	model "github.com/pah-dev/fast-track-quiz/api/models"
)

var Questions = []model.Quiz{
	{
		Id: 1,
		Question:  "JSON elements are separated by the ___",
		Opt1:  "line break",
		Opt2:  "semi-colon",
		Opt3:  "comma",
		Opt4:  "white space",
		Answer:  3,
	},
	{
		Id: 2,
		Question:  "A _____ indicates an absent value that may exist but be unknown or that may not exist at all.",
		Opt1:  "Empty tuple",
		Opt2:  "New value",
		Opt3:  "Null value",
		Opt4:  "Old value",
		Answer:  3,
	},
	{
		Id: 3,
		Question:  "SELECT name FROM instructor WHERE salary IS NOT NULL; Selects",
		Opt1:  "Tuples with null value",
		Opt2:  "Tuples with no null values",
		Opt3:  "Tuples with any salary",
		Opt4:  "All of the mentioned",
		Answer:  2,
	},
	{
		Id: 4,
		Question:  "JSON stands for ________________",
		Opt1:  "Java Standard Output Network",
		Opt2:  "JavaScript Object Notation",
		Opt3:  "JavaScript Output Name",
		Opt4:  "Java Source Open Network",
		Answer:  2,
	},
	{
		Id: 5,
		Question:  "Which is correct format of writting JSON name/value pair",
		Opt1:  "'name : value'",
		Opt2:  "name = 'value'",
		Opt3:  "name = \"value\"",
		Opt4:  "\"name\" : \"value\"",
		Answer:  4,
	},
	{
		Id: 6,
		Question:  "Which of the following is not a type in JSON?",
		Opt1:  "date",
		Opt2:  "Object",
		Opt3:  "Array",
		Opt4:  "string",
		Answer:  1,
	},
	{
		Id: 7,
		Question:  "Is JSON Case sensitive?",
		Opt1:  "Yes",
		Opt2:  "No",
		Opt3:  "Maybe",
		Opt4:  "IDK",
		Answer:  1,
	},
	{
		Id: 8,
		Question:  "What are two main structures compose JSON?",
		Opt1:  "Arrays and Objects",
		Opt2:  "Keys and values",
		Opt3:  "Class and Objects",
		Opt4:  "None of above",
		Answer:  2,
	},
	{
		Id: 9,
		Question:  "JSON strings have used in___.",
		Opt1:  "Double quote",
		Opt2:  "Single quote",
		Opt3:  "Both 1 & 2",
		Opt4:  "None of These",
		Answer:  1,
	},
	{
		Id: 10,
		Question:  "What is the common usage of Json on modern websites?",
		Opt1:  "To send and receive bits of data",
		Opt2:  "To store information remotely",
		Opt3:  "To store information locally",
		Opt4:  "All of the Above",
		Answer:  1,
	},
	{
		Id: 11,
		Question:  "Which of the following code will throw an error?",
		Opt1:  "JSON.parse(‘{}’);",
		Opt2:  "JSON.parse(null);",
		Opt3:  "JSON.parse(undefined);",
		Opt4:  "JSON.parse(‘{}’);",
		Answer:  3,
	},
	{
		Id: 12,
		Question:  "Which of the following Protocol services uses JSON?",
		Opt1:  "SMTP",
		Opt2:  "HTTP",
		Opt3:  "TCP/IP",
		Opt4:  "Web Protocol",
		Answer:  2,
	},
	{
		Id: 13,
		Question:  "JSON is derived from the ______ programming language?",
		Opt1:  "Java",
		Opt2:  "ECMScript",
		Opt3:  "PHP",
		Opt4:  "JavaScript",
		Answer:  4,
	},
	{
		Id: 14,
		Question:  "Which of the following is the limitation of JSON?",
		Opt1:  "Too many data types",
		Opt2:  "Complicated debugging",
		Opt3:  "Support for only C",
		Opt4:  "No limit on arrays and objects",
		Answer:  2,
	},
	{
		Id: 15,
		Question:  "Which of the following JSON feature ensures communication between two applications designed in different programming languages?",
		Opt1:  "Extensibility",
		Opt2:  "Scalability",
		Opt3:  "Interoperability",
		Opt4:  "Reusability",
		Answer:  3,
	},
	{
		Id: 16,
		Question:  "Qale funzione in PHP si usa per convertire i dati in un formato JSON ?",
		Opt1:  "php_encode",
		Opt2:  "php_string_to_json",
		Opt3:  "php_decode",
		Opt4:  "json_codify",
		Answer:  1,
	},
	{
		Id: 17,
		Question:  "Qale funzione si usa in PHP per convertire il formato JSON in dati alfanumerici?",
		Opt1:  "json_encode",
		Opt2:  "json_to_string",
		Opt3:  "json_decode",
		Opt4:  "json_to_array",
		Answer:  3,
	},
	{
		Id: 18,
		Question:  "La base del formto JSON è una struttura chiave:valore dove chiave rappresenta il campo di dati e il valore rappresenta l'informazione",
		Opt1:  "Vero",
		Opt2:  "Falso",
		Opt3:  "Null",
		Opt4:  "Nil",
		Answer:  1,
	},
	{
		Id: 19,
		Question:  "How many types of json data?",
		Opt1:  "6",
		Opt2:  "4",
		Opt3:  "7",
		Opt4:  "3",
		Answer:  1,
	},
	{
		Id: 20,
		Question:  "Which of these is proper a JSON array?",
		Opt1:  "{ “letters” : { “a”, “b”, “c”; } }",
		Opt2:  "{ ‘letters’ : {“a”, “b”, “c” } }",
		Opt3:  "{ “letters” : { a, b, c } }",
		Opt4:  "{ “letters” : { “a”, “b”, “c” } }",
		Answer:  4,
	},
	{
		Id: 21,
		Question:  "What is the return type of the method parseInt()?",
		Opt1:  "String",
		Opt2:  "Float",
		Opt3:  "Integer",
		Opt4:  "Date",
		Answer:  3,
	},
	{
		Id: 22,
		Question:  "In JavaScript, what is a block of statement?",
		Opt1:  "Conditional block",
		Opt2:  "Block that combines a number of statements into a single compound statement",
		Opt3:  "Both conditional block and a single statement",
		Opt4:  "Block that contains a single statement",
		Answer:  2,
	},
	{
		Id: 23,
		Question:  "The 'function' and 'var' are known as:",
		Opt1:  "Keywords",
		Opt2:  "Data types",
		Opt3:  "Declaration statements",
		Opt4:  "Prototypes",
		Answer:  3,
	},
	{
		Id: 24,
		Question:  "JSON strings have to be in",
		Opt1:  "single quote",
		Opt2:  "double quote",
		Opt3:  "Double quote",
		Opt4:  "Single quote",
		Answer:  2,
	},
	{
		Id: 25,
		Question:  "Give an example of JSON object?",
		Opt1:  "Data is in name/value pairs",
		Opt2:  "Data is separated by comma",
		Opt3:  "Curly brackets hold objects",
		Opt4:  "Square bracket holds arrays",
		Answer:  4,
	},
	{
		Id: 26,
		Question:  "Why must one use JSON over XML?",
		Opt1:  "It is faster and lighter than XML as on the wire data format",
		Opt2:  "XML data is typeless while JSON objects are typed",
		Opt3:  "JSON types: Number, Array, Boolean, String",
		Opt4:  "XML data are all string",
		Answer:  2,
	},
	{
		Id: 27,
		Question:  "What are the data types supported by JSON?",
		Opt1:  "Number",
		Opt2:  "String",
		Opt3:  "Boolean",
		Opt4:  "Array",
		Answer:  1,
	},
	{
		Id: 28,
		Question:  "Which of these is correct about the JSON standard?",
		Opt2:  "It is an open standard",
		Opt3:  "It is privately developed",
		Opt4:  "It requires a license to use",
		Answer:  1,
	},
	{
		Id: 29,
		Question:  "In modern websites what is the common usage for JSON?",
		Opt2:  "To store information remotely.",
		Opt3:  "To send and receive bits of data.",
		Opt4:  "To store information locally.",
		Answer:  2,
	},
	{
		Id: 30,
		Question:  "What is the purpose of the method JSON.parse()?",
		Opt1:  "Parses a string to integer",
		Opt2:  "Parses a string to JSON",
		Opt3:  "Parses a string from JSON to JSON2",
		Opt4:  "Parses integer to string",
		Answer:  2,
	},
	{
		Id: 31,
		Question:  "Can you use a double quote inside a JSON string?",
		Opt1:  "Yes, if you use the ascii code.",
		Opt2:  "Yes, you can use it without any special treatment",
		Opt3:  "Yes, if it is escaped like ( \\\" )",
		Opt4:  "No, you should use single quotes",
		Answer:  3,
	},
	{
		Id: 32,
		Question:  "What is the MIME type of JSON?",
		Opt1:  "application/x-json",
		Opt2:  "text/json",
		Opt3:  "application/json",
		Opt4:  "application/javascript",
		Answer:  3,
	},
	{
		Id: 33,
		Question:  "Which of these is supported as a JSON Value type?",
		Opt1:  "Infiniti",
		Opt2:  "Null",
		Opt3:  "Undefined",
		Opt4:  "NaN",
		Answer:  2,
	},
	{
		Id: 34,
		Question:  "Which is the file extension of JSON?",
		Opt1:  ".js",
		Opt2:  ".json",
		Opt3:  ".java",
		Opt4:  ".jpg",
		Answer:  2,
	},
	{
		Id: 35,
		Question:  "Is whitespace matter in JSON?",
		Opt1:  "No, it will be stripped out.",
		Opt2:  "Yes, both inside and outside of strings",
		Opt3:  "Yes, only within strings",
		Opt4:  "Yes, only outside of strings",
		Answer:  3,
	},
	{
		Id: 36,
		Question:  "Who is the creator of JSON?",
		Opt1:  "Sergey Brin",
		Opt2:  "Douglas Crockford",
		Opt3:  "Liam Crockford",
		Opt4:  "None of these",
		Answer:  2,
	},
	{
		Id: 37,
		Question:  "Which of the following is the fastest JavaScript parser?",
		Opt1:  "Acron",
		Opt2:  "JSLint",
		Opt3:  "Esprima",
		Opt4:  "Traceur",
		Answer:  1,
	},
	{
		Id: 38,
		Question:  "What is JSON data?",
		Opt1:  "Exchanging data",
		Opt2:  "Non-exchanging data",
		Opt3:  "Changing data",
		Opt4:  "None of these",
		Answer:  1,
	},
}